services:
  otel-lgtm:
    image: grafana/otel-lgtm
    container_name: grafana-otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    restart: unless-stopped
